spring.application.name=devsu
server.port=5001


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


logging.level.root=INFO
logging.level.com.bank.devsu=DEBUG


spring.web.cors.allowed-origins=http://localhost:4200,http://localhost:80
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true


cuenta.limite-diario-retiro=2100

spring.profiles.active=sqlserver

